vergecurrency/verge

src/rpcwallet.cpp
This uses the same method as getmininginfo now.
GetDifficulty is already setup to handle a zero argument condition
=> Make RPC getinfo's difficulty reporting consistant

src/rpcblockchain.cpp
- fix GetLastBlockIndex4Algo()
- fix GetDifficulty to work on the specified algo
Also makes solo and wallet (?) mining possible.
Can be deployed without hardfork.
=> RPC difficulty fixes

src/qt/bitcoingui.cpp
Was causing a compiler error. Just added blank strings rather than leaving out the argument entirely
=> Fix for invalid constructor method arguments for QIcon

.travis.yml, building/mac/build.sh, building/mac/dist.sh, building/mac/requirements.sh
This PR:
- updates the build to use a newer version of Xcode in Travis
- Fixes build scripts so they work on OS X 10.12
- Removes the need to download the old ruby homebrew install script
=> Fixing OS X Build

README.md
- fix mac qt download link
- update qt version to match version in build.sh
- remove extra trailing whitespaces
=> fix for issue 166 (mac qt download link & version)

src/qt/forms/optionsdialog.ui
Fix for https://github.com/vergecurrency/VERGE/issues/259
Realigned the label on top of the drop down
As well moved the Start Verge on System Login checkbox to the bottom of the Tab panel
=> Fix for https://github.com/vergecurrency/VERGE/issues/259

src/qt/editaddressdialog.cpp, src/qt/forms/editaddressdialog.ui
Currently (after we removed the address from new address dialog) the "Address" label is unwanted
After this change:
Also, edit address will work normally (this PR does not affect this)
=> remove unwanted UI element on new address

README.md, doc/build-verge-linux.md, doc/build-verge-osx.md, doc/build-verge-win.md, doc/dev-notes.md
1. As a newcomer myself, I thought it would be handy to have some form of doc dedicated to devs. I created an initial one with stuff I've learned so far. Hopefully, more experienced VERGE devs can add useful things here for us newbies.
2. Other part is that I moved out the build/compile instructions for all systems into ./doc instead, as I felt the readme was very heavy with text. This was just an idea for making the readme a bit more compact.
/ Max
=> Add initial dev notes and move build instructions to doc instead.

src/qt/forms/aboutdialog.ui
Before:
After:
Removed the stylesheet from the button. It's causing buttons to look like label, the default Qt styles look nicer and has a clickable feel to it (hoping we could keep this consistent throughout)
=> Fix about dialog

src/net.cpp, src/qt/sendcoinsdialog.cpp, src/wallet.cpp
This PR helps with removing few warnings during compilation.
Removed the currently unused ThreadStakeMinter as ThreadVERGEMiner does the exact same thing. If this was wrong to do, let me know.
/ Max
=> Removing compiler warnings

src/wallet.cpp
Cannot rename address label #437 
Cannot edit the label of stealth address on MacOS #447 
tested on macOS High Sierra
=> Fixes a bug where you aren't able to relabel stealth addresses

src/init.cpp, src/main.cpp, src/main.h, src/txdb-leveldb.cpp, src/txdb-leveldb.h, src/wallet.cpp
Solves #318 - Adding a loading indicator for showing current load procedure 
#318 WP: Add progress indicator on splash screen while loading blockchain
Has been test on MacOS High Sierra (PRO), no performance issue.
Clearly lightweight percentage indicator on splash screen.
=> #318 Adding a loading indicator for showing current load procedure 

building/mac/requirements.sh
Fixed requirements.sh to explicitly brew install libevent
Added brew install libevent
https://github.com/vergecurrency/VERGE/issues/471
Make it easier to build mac locally.
Tested it locally and it worked.
=> (fix): Added libevent brew installation for mac building of requirements

src/qt/bitcoingui.cpp, src/qt/bitcoingui.h, src/rpcwallet.cpp
Fix walletlock command and adds possbility of locking in menubar/traysettings.
Fixes #497 
Ubuntu 16.04 with testnet
For some reason pwalletMain->Lock(); was commented out in the walletLock function in commit 1a171d93551455d839867f714ebacff4a07dacbd
The names of the unlockWallet/unlockWalletForMinting that call setWalletLock() are bit confusing as setWalletLock will just flip the lock depending on its state. So I added a lockWalletAction which currently uses the same function as unlockWalletAction. Thought id upload the initial fix and then a discussion about the naming could be had perhaps?
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [x ] My code follows the code style of this project.
=> Fix wallet lock problem

building/linux/build.sh, doc/build-verge-linux.md
Updating linux build doc  https://github.com/vergecurrency/VERGE/blob/master/building/linux/requirements.sh#L9
(seems we need libcap-dev)
Also, adding make clean before make just so any previous remains are cleaned up.
=> update linux build instruction, make clean

go.sh
go.sh: ./configure: not found, Ubuntu was skiping line to run ./autogen.sh which was causing the ./configure error. changed code to install file accordingly (removing sh). Also added missing dependencies and cleaned up list.
previous commit for Update go.sh will be removed. This fixes all issues with go.sh
go.sh was failing when installing on Ubuntu.
Ran on personal machine under Ubuntu, will run on another machine and comment below if works.
=> Update go.sh dependencies and ./autogen issue

src/qt/bitcoinamountfield.cpp, src/qt/bitcoinamountfield.h, src/qt/bitcoinunits.cpp, src/qt/bitcoinunits.h, src/qt/forms/sendcoinsentry.ui, src/qt/sendcoinsentry.cpp, src/qt/sendcoinsentry.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h
Continuation of  @marpme PR #494 as I have no write permissions. Issue was that BitcoinUnits::format "formats" with commas since commit 6a3f25ba7aad1c004d1bd7cf09d8cf5b70f07259 , and this does not work well with a Spinbox.
Question is. Do we want a 75% button as well?
Adds a flag to BitcoinUnits::format that allows formatting without any commas.
Closes #406 
Ubuntu 16.04
Have tested so that 25% 50% and 100% outputs correct values.
=> Feature automatic transfer amount selection (fixed)

src/qt/forms/sendcoinsentry.ui, src/qt/sendcoinsentry.cpp, src/qt/sendcoinsentry.h, src/qt/walletmodel.cpp, src/qt/walletmodel.h
Adds the option to set 25%, 50% or 100% of your current balance as your transaction balance.
#406 Enhancement Request Template
Must be tested with certain balances.
=> Feature automatic transfer amount selection

src/netbase.cpp
Unsure if this code ever properly worked since it's copying the wrong magic bytes.
The garlicat magic bytes have been incorrect since original import.
No related issue, however if this isn't considered important it might be worth just removing the excess code.
This code cannot properly work as designed with the current code.
Just code analysis.
=> Fix memcpy of garlicat to actually be garlicat

src/bitcoinrpc.cpp, src/bitcoinrpc.h, src/rpcwallet.cpp
With this you will be able to export a stealth address
by a given address or a label.
See issue/feature #662 
compiled and tested on ubuntu 16.04 LTS
=> Added a new rpc command for exporting stealth addresses

src/main.cpp, src/rpcsmessage.cpp, src/smessage.cpp, src/wallet.cpp
Travis compile errors out now on Mac builds.  Linux and Windows threw warnings, but Mac compiles throws error.
**Mac Build:**
main.cpp:1980:34: **_error_**: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]
**Linux / Win builds:**
main.cpp:1980:20: **_warning_**: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
=> fixing new Travis Mac Compile error - C++11 requires a space between literal and string macro

go.sh
Sudo Causing tor to not ./configure correctly when running ./autogen.sh as sudo
Removed Sudo before ./autogen.sh  This was causing tor to be installed as Sudo and causing Initializing the tor installation error: 
"config.status: creating contrib/dist/suse/tor.sh
mv: cannot move './confE6vHIf/out' to 'contrib/dist/suse/tor.sh': Permission denied
config.status: error: could not create contrib/dist/suse/tor.sh
configure: error: ./configure failed for tor"
Testing on local machine Ubuntu 16.04
=> Sudo Causing Tor to require admin privileges

src/bitcoinrpc.cpp, src/bitcoinrpc.h, src/rpcblockchain.cpp, src/rpcnet.cpp
Those calls are used by other software to receive information which was only available through the getinfo call in ancient bitcoin codebases before 2013.
=> Add rudimentary support for getnetworkinfo and getblockchaininfo RPC

src/txdb-leveldb.cpp
Flushing buffers is necessary since the wallet needs to read in the output of this process and it can't do it unless the buffer is constantly flushed.
=> Flush buffers for new wallet

src/rpcwallet.cpp, src/txdb-leveldb.cpp
The new wallet needs a standard way of handling locking and unlocking the wallet.
So therefor I added a `isunlocked` field to quickly check if the wallet is really locked or not.
Kept the old option for backward compatibility.
=> Adding additional output for the getinfo command

depends/packages/zeromq.mk
This is related to the BTC issue
https://github.com/bitcoin/bitcoin/pull/15188
and CVE https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-6250
=> Update zeromq to 4.3.1 (#874)

src/rpc/mining.cpp
=> Bugfix 897 get hash power via rpc calls

src/chainparams.cpp
* better initial connection establishment
* dynamically adding new verge nodes, without releasing core versions or adding nodes manually
For me, it highly improves the finding mechanism to reach new peers without having any static peers in either peers.dat nor inside the config (clearnet).
=> Add DNS seeds with dynamic peer lists which will resolve in verge hosts

src/core_write.cpp, src/miner.cpp, src/miner.h, src/rpc/rawtransaction.cpp, src/validation.cpp
Transaction time should not be newer than the block itself.
Thank you V4 for this great rule, it's just applicable for POS chains.
Thus we also need it in the new V5.
=> Transaction timing for block creation

src/coins.cpp, src/coins.h, src/consensus/tx_verify.cpp, src/test/coins_tests.cpp, src/txdb.cpp, src/txmempool.cpp
Tx inputs should NOT be younger than the inputs for the transactions itself.
No value-added, just V4 compatibility. :)
=> Bugfix time inputs versus time transaction

src/rpc/mining.cpp
Opens for miners the possibility to choose what algorithm is currently being interesting and they need a template for. With this change, you now can pass a parameter called `algo` into the common request structure to retrieve a block specifically for this algorithm.
Moreover, it is saving them a lot of resources and thus money as they don't have to host 5 different verge nodes.
=> Update multi-algo template composition

.gitmodules, configure.ac, src/Makefile.am
Features:
* upgrades tor to the latest version
* adds the capability for using custom OpenSSL versions and pass it to tor compiling
=> Upgrade Tor from version 0.3.5.8 to version 0.4.1.6

src/Makefile.am, src/alerter.cpp, src/alerter.h, src/net_processing.cpp, src/validation.cpp
Adds a new alert whenever we met a peer with an unknown higher protocol version that we're able to support. With that we are going to tell the user via `alertnotify`-cmd or visually inside the QT Wallet to manually check for wallet upgrades. (no website or links specified for REASONS.)
What it's not:
* an automatic upgrade mechanism
* referrer to any wesbite to download something
* downgrades compatiblity
=> Add protocol version alert when connected to peer

src/verge-cli.cpp
Add the _-version_ option to verge-cli. 
This is useful for administrators and anyone else building automation tasks. It provides consistency with many other coin daemons, simplifying the process of being able to run the same tool against multiple daemons without having to cater for special cases (like getting the version information from the daemon instead).  
[#1063](https://github.com/vergecurrency/verge/issues/1063)
Makes life easier for automation builders by providing consistency with other coins.
Forked, branched, compiled, tested. The functionality was actually already present in verge-cli; I have just exposed it. The change is self-documenting, as can be seen in the screenshot below 
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the code …
=> Add -version option to verge-cli

.github/workflows/check-commit.yml, .gitmodules
=> Upgradetor
