src/qt/serveur.cpp
pls dev this really cheeses me off
doesn't seem to cause issues but i don't really know what i'm doing
=> Fix for spaces being replaced by full stops in the IRC client

src/qt/forms/chatwindow.ui
These changes fix the chat window login screen and adds proper spacing
as well as help commands.
=> Chat window modifications

src/qt/chatwindow.cpp, src/qt/serveur.cpp
fixes size of window and adds commands
=> chat window updates

README.md, configure.ac, src/Makefile.am
It's quicker to have travis double check that it compiles on linux, so I didn't test a linux build.
=> Compile on mac

README.md, contrib/docker/Dockerfile, contrib/docker/README.md
created Dockerfile and README that shows how to use it
=> Docker info and fix markup on base README

src/init.cpp
The previous listed defaults were old and unused ports.
=> Update default port/rpcport in init help message

contrib/docker/README.md, contrib/docker/centos7/Dockerfile, contrib/docker/centos7/README.md, contrib/docker/debian8/Dockerfile, contrib/docker/debian8/README.md, contrib/docker/ubuntu14/README.md, releases.txt
=> updating the docker images for 2.1.0

README.md, share/qt/Info.plist.in
=> Minor updates

README.md, configure.ac, contrib/docker/arch/Dockerfile, contrib/docker/arch/README.md, contrib/docker/fedora23/Dockerfile, contrib/docker/fedora23/README.md, releases.txt
- new dockers (arch and fedora)
- configure.ac requires update
- minor changes to README.md to make it look better
=> More dockers

go.sh
Backup of wallet.dat in home directory
Add some addnode in VERGE.conf generator
Checksum verifications in vergecurrency.com. later in vergecurrency.de  zip file or site (md5 optional)
=> missing addnodes from VERGE.conf and more

go.sh
verge-blockchain.com provides a static link now  to download the latest Blockchain
=> simplify go.sh by using static download link

contrib/docker/centos7/Dockerfile, contrib/docker/ubuntu14_container/Dockerfile, contrib/docker/ubuntu14_container/README.md, contrib/docker/ubuntu14_container/conf/VERGE.conf, contrib/docker/ubuntu14_container/docker-compose.yml
better ubuntu with compose example
working centos
=> Updated docker files

go.sh, src/Makefile.qt.include, src/qt/bitcoin.qrc, src/wallet.h
Notes:
1. Removed radio.png and chat.png references from project since it doesn't appear to be used anymore (See issue [138](https://github.com/vergecurrency/VERGE/issues/138) and commit [efa30d9]( https://github.com/vergecurrency/VERGE/commit/efa30d90f24b293d2b6f2eb7f48fcad78dd2c52a))
2. Commented out CWallet::Lock() prototype from wallet.h since there is no implementation and the parent class already has an implementation (unless there are plans to override this method...)
3. Some small file checking and directory creation check in go.sh to prevent some errors that may be misleading.
=> Fix linux build errors

src/stealth.cpp
It was pointed out on Reddit that a few typos existed, thought I'd take this opportunity to contribute :)
Keep up the good work!
=> Fix typos in stealth.cpp

README.md
Just cleaned up the snippets to make the markdown consistant.
Fan of the project. Cheers!
=> tidy up the readme

contrib/easywinbuilder/set_vars.bat, contrib/gitian-descriptors/deps-linux.yml, contrib/gitian-descriptors/deps-win.yml, contrib/gitian-descriptors/gitian-osx-depends.yml, doc/build-unix.txt, doc/build-verge.sh, src/base58.h, src/bignum.h, src/crypter.cpp, src/key.cpp, src/m4/bitcoin_qt.m4, src/script.cpp, src/smessage.cpp
DISCLAIMER: THIS IS NOT RELATED TO WRAITH.
Hello, I present an attempt to use openssl1.1 in Verge. This has been done mainly because of the problems with building Verge on Fedora 27
=> initial support for openssl1.1

contrib/easywinbuilder/set_vars.bat, contrib/gitian-descriptors/deps-linux.yml, contrib/gitian-descriptors/deps-win.yml, contrib/gitian-descriptors/gitian-osx-depends.yml, doc/build-unix.txt, doc/build-verge.sh, src/base58.h, src/bignum.h, src/crypter.cpp, src/key.cpp, src/m4/bitcoin_qt.m4, src/openssl_compat.h, src/script.cpp, src/smessage.cpp
DISCLAIMER: NOT RELATED TO WRAITH!
As we discussed - added backward compatibility for openssl 1.0
=> openssl 1.1 support with 1.0.2 compatibility

src/qt/bitcoingui.cpp
Fix portions of: https://github.com/vergecurrency/VERGE/issues/190
Before:
After:
Also fixes, context menu of File -> Export...
=> fix context menu issue

configure.ac, src/keystore.cpp, src/qt/bitcoinaddressvalidator.h, src/qt/forms/sendcoinsentry.ui, src/qt/walletmodel.cpp, src/wallet.cpp, src/walletdb.cpp
Hey,
addresed following issues:
- stealth addresses disappearing after restart
- truncation of stealth address when paste into send addr edit box
- create transaction error for stealth transactions
- unlocking
One more commit for stealth transactions will be probably necessary as we discussed.
=> Fix numerous submitted issues

src/init.cpp
fixes #203 
Very new to the code base, so as mentioned in #203, if there are any other missing --help options, kindly let me know.
=> Updating --help options

src/qt/locale/bitcoin_tr.ts
Turkish translation of VERGE wallet app.
[70% translation finished.]
=> Turkish translation

src/qt/walletmodel.cpp, src/wallet.cpp
Additional stuff for stealth tx. With Ahmed's changes stealth should be done.
=> more fixes for stealth tx

src/script.cpp
With this stealth tx makes it to the mem pool.
=> fixed stealth tx

doc/build-verge-linux.md
Tested on a clean Fedora 27 install.
=> Add build instructions for Fedora

src/qt/transactionrecord.cpp
=> hide additional part of stealth tx with 0 amount and no addr

src/Makefile.qt.include, src/qt/bitcoin.cpp, src/qt/bitcoin.qrc, src/qt/bitcoin_locale.qrc, src/qt/locale/bitcoin_es.ts, src/qt/locale/bitcoin_nl.ts
Hi @justinvforvendetta 
to make the multilingual work properly:
- I created a bitcoin_locale.qrc file dedicated for translations (note inside that the file extension must be .qm not .ts) 
- I adjusted Makefile.qt.include and bitcoin.cpp accordingly
- I have also fixed some bugs in es and nl files to make compiling succeed
I point out that the base file bitcoin_en.ts is not correct because it is not updated with the latest changes made to the application, so not even all the translation files are correct.
Cheers
Stefano
=> fixing translation engine

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> Adding issue and pull request template

src/script.h
This is a Backport of the [fix](https://github.com/bitcoin/bitcoin/pull/7907) from **Bitcoin Core v0.12.1**  
More info regarding the bug can be found here: [A Bitcoin transaction that takes 5 hours to verify](https://bitslog.wordpress.com/2017/01/08/a-bitcoin-transaction-that-takes-5-hours-to-verify/)
Not sure if already on your radar, but here it is. If redundant, feel free to ignore it.
Kind regards,
=> backport: Bitcoin - optimize CScript.FindAndDelete

src/qt/transactionview.cpp
removed StakeMint Item from the item list
=> Fix for #349

src/net.cpp, src/qt/forms/aboutdialog.ui, src/qt/sendcoinsdialog.cpp, src/wallet.cpp
@Sach97
Sach97
adding issue and pull request template
ca8b60c
Commits on Jan 04, 2018
@dbtftw
dbtftw
Fix for #349  …
c2f593d
@brakmic
brakmic
backport: Bitcoin - optimize CScript.FindAndDelete
401babc
@Max-Meldrum
Max-Meldrum
Remove duplicated and unused func ThreadStakeMinter
207e93b
@Max-Meldrum
Max-Meldrum
Remove unused variable in ChangeWalletPassphrase
d8523ab
@Max-Meldrum
Max-Meldrum
Remove compiler warning in switch case
7bcdabe
Commits on Jan 05, 2018
@brakmic
brakmic
Merge branch 'master' into fix-script
508f611
Commits on Jan 07, 2018
@justinvforvendetta
justinvforvendetta
Merge pull request #327 from Sach97/master  …
Verified
b04499e
@justinvforvendetta
justinvforvendetta
Merge pull request #366 from brakmic/fix-script  …
Verified
fcec96d
@justinvforvendetta
justinvforvendetta …
=> merge master into tor

Makefile.am, building/mac/build.sh, building/mac/requirements.sh, configure.ac, src/util.h
=> more osx updates

doc/build-verge-linux.md, doc/build-verge-osx.md, go.sh
1. Update git clones to include --recurse-submodules, to handle tor submodule.
2. Small addition (git install and git clone) in os x build.
Cheers
=> Add fetch of submodules

src/main.cpp, src/txdb-leveldb.cpp
Referes to PR #460 
tested on macOS High Sierra
=> Fixes restart bug with empty database

src/main.cpp
Updated block number in 'stealth tx disabled' error message to reflect new stealth soft fork at 1824150
=> updated block number in 'stealth tx disabled' error message

contrib/docker/centos7/Dockerfile, contrib/docker/fedora23/Dockerfile, contrib/docker/fedora27/Dockerfile, contrib/docker/fedora27/README.md
Updated docker files for centos7 and fedora23 to the latest package requirements.
Added an additional docker file for fedora27.
=> Updated some docker files

src/qt/forms/sendcoinsentry.ui, src/qt/sendcoinsentry.cpp, src/qt/sendcoinsentry.h
As VERGE is a community driven project, this PR adds a button where users can easily donate to support future developments.
Address being connected is:
`DDd1pVWr8PPAw1z7DRwoUW6maWh5SsnCcp`
Ubuntu 16.04
Has not been tested on Win/OS X
=> Add donation option

src/Makefile.qt.include, src/qt/bitcoingui.cpp, src/qt/bitcoingui.h, src/qt/faqdialog.cpp, src/qt/faqdialog.h, src/qt/forms/faqdialog.ui
This PR adds a FAQ section.
I just added some Q/A's, feel free to correct/add.
And regarding the choice of icon. I didn't really see any that would fit FAQ. Went with block.png (this can probably be improved)
Ubuntu 16.04
Should probably be tested on Win/OS X as well.
=> Add FAQ section

README.md
precompiled linux not offered.  change to compile from source
=> remove reference to linux precompile in readme.md

README.md
Added the title back to the "easy way" and Added notes to remind users to ensure permissions are set up on the default user to do this install.
Linux install issues when users do not have permissions set up properly.
Fixes deleted text that was in the README file.
N/A
=> update linux install "Easy Way"

README.md
Forgot to remove this while submitting #575 
Cheers
=> remove osx boost deps install instruction

src/qt/locale/bitcoin_fr.ts
Thanks to wertzuiop123 here is a DE ranslation file
=> Add DE translation

src/qt/locale/bitcoin_cn.ts
Chinese Simplified translation
=> add bitcoin_cn.ts

src/Makefile.qt.include, src/qt/bitcoin_locale.qrc, src/qt/locale/bitcoin_de.ts, src/qt/locale/bitcoin_el.ts, src/qt/locale/bitcoin_es.ts, src/qt/locale/bitcoin_it.ts, src/qt/locale/bitcoin_nl.ts, src/qt/locale/bitcoin_ptBR.ts, src/qt/locale/bitcoin_ro.ts, src/qt/locale/bitcoin_ua.ts
file | language | pull req | in master | bitcoin_locale.qrc | makeflile.qt.inc | merged | Just TS Files?
-- | -- | -- | -- | -- | -- | -- | --
bitcoin_ptBR.ts | brazilian portuguese | 303 |   |   |   |   | no
bitcoin_cn.ts | chinese | 420 | x |   |   | 3/26/2018 |  
bitcoin_nl.ts | dutch | 329 | x | x | x |   | yes
bitcoin_nl.ts | dutch | 332 | x | x | x |   | yes
bitcoin_nl.ts | dutch | 363 | x | x | x |   | yes
bitcoin_nl.ts | dutch | 384 | x | x | x |   |  
bitcoin_en.ts | english | NA | x | x | x |   |  
bitcoin_fr.ts | french | 333 | x | x | x |   | yes
bitcoin_de.ts | german | 311 | x |   |   | 3/26/2018 |  
bitcoin_el.ts | greek | 359 |   |   |   |   |  
bitcoin_it.ts | italian | 319 | x |   |   | 3/26/2018 |  
N/A | N/A | 368 | x |   |   |   |  
bitcoin_nb.ts | Norwegian |   | x | …
=> All new/updated translations and include files

README.md
Update the dead links of the readme to be compatible with the new website for : 
- Mining Pool List
- Black Paper
=> Update readme with links for the new website

src/txdb-leveldb.cpp
See issue #663
compiled & tested on Ubuntu 16.04 LTS
=> Adds a loading indicator for VERGEd node process

.travis.yml
=> Fix travis build randomly failing

src/qt/locale/bitcoin_cn.ts, src/qt/locale/bitcoin_de.ts, src/qt/locale/bitcoin_el.ts, src/qt/locale/bitcoin_en.ts, src/qt/locale/bitcoin_es.ts, src/qt/locale/bitcoin_fr.ts, src/qt/locale/bitcoin_it.ts, src/qt/locale/bitcoin_nb.ts, src/qt/locale/bitcoin_pl.ts, src/qt/locale/bitcoin_ptBR.ts, src/qt/locale/bitcoin_ro.ts, src/qt/locale/bitcoin_ru.ts, src/qt/locale/bitcoin_tr.ts, src/qt/locale/bitcoin_ua.ts, src/qt/transactiondesc.cpp
=> update text : 25 block confirmation to 140

CONTRIBUTING.md
=> *Trivial* Minor correction

building/mac/build.sh, building/mac/requirements.sh, src/rpcwallet.cpp
@justinvforvendetta I really like you, but next time leave a todo 💃 😆
=> Locking wallet automatically/manually

configure.ac, src/Makefile.bench.include, src/init.cpp, src/net.h, src/net_processing.cpp, src/protocol.cpp, src/torcontrol.cpp, src/torcontrol.h, src/torcontroller.cpp, src/torcontroller.h
=> [Bugfix-841] Fix tor connection issues

src/init.cpp, src/torcontroller.cpp, src/torcontroller.h
=> Improve thread handling for tor

COPYING, LICENSE
=> *doc* Update MIT Lic

src/chainparams.cpp, src/consensus/params.h, src/validation.cpp, src/validation.h
Tests are missing, I will see if I can write some test for those small things
=> Add missing block validation checks (missing forks)

src/wallet/crypter.cpp, src/wallet/wallet.cpp, src/wallet/wallet.h, src/wallet/walletdb.cpp
=> Bugfix stealth encrypted wallet

go.sh, src/chainparams.cpp, src/net_processing.cpp, src/primitives/block.cpp, src/primitives/block.h, src/validation.h
=> Improved header and block network processing

go.sh, src/chainparams.cpp
=> merge master

src/net_processing.cpp, src/primitives/block.cpp, src/primitives/block.h, src/validation.h
Processing improvements for receiving and processing headers and blocks
This change enables for consistent transferring and processing of new headers.
=> [WIP] Improved header and block network processing

src/validation.cpp
=> Add special block signature check for blocktemplate

src/rpc/mining.cpp, src/validation.cpp, src/validation.h
resolves #963 
Adds capability to for miner to identify, if mining right now would make any sense cause of our mining consensus regarding the < 5 blocks of the same algorithm in a row.
=> Mining availability for certain algorithm

README.md
Change the readme build status badge to stable green
=> Update readme build badge to stable

configure.ac, src/chainparams.cpp, src/net.cpp, src/netbase.cpp, src/netbase.h, src/rpc/mining.cpp
=> Basic integration of TOR DNS seeding via TXT records

.github/workflows/build-test-ubuntu-no-wallet.yml, .github/workflows/build-test-ubuntu.yml, src/rpc/mining.cpp
* adds a check if the wallet is disabled and if so, then do not include the wallet anyways.
=> Check if wallet is enabled and add wallet inclusion

src/util/strencodings.cpp
Bittrex request to being able to actually parse more than 6 digits but throw the rest away :D
=> Add the possiblity to parse more than 6 trailing digits

src/util/strencodings.cpp
Reverts vergecurrency/VERGE#1001
=> Revert "Add the possiblity to parse more than 6 trailing digits"

src/version.h
=> Raise the minimum peer version to protocol-90008

src/qt/addresstablemodel.cpp, src/stealth.cpp
Request for unlocking the wallet before creating a new stealth address.
And removing sensitive data from debug.logs (pubkeys)
=> Fix unlocking GUI when creating a new stealth address

README.md, src/chainparams.cpp
Needed in order to seed testnet when no other nodes are available
=> Adds new onion address for testnet and updates README.md

.circleci/config.yml, contrib/gitian-build.py
updates circle-ci config to use CIRCLE_PROJECT_USERNAME
=> Updates gitlian-build.py to vergecurrency owned fork

.circleci/config.yml, contrib/gitian-build.py
=> updates sha256sum in gitlian-build.py

src/qt/messagemodel.cpp, src/secp256k1/src/modinv32_impl.h, src/secp256k1/src/modinv64_impl.h, src/secp256k1/src/secp256k1.c
=> chore: remove repetitive words

.gitmodules
new version of tor
we now pull from [torproject.org's git lab repository](https://gitlab.torproject.org/)
=> Upgradetor

src/policy/feerate.cpp, src/qt/test/util.h, src/secp256k1/src/ecmult_const_impl.h, src/wallet/crypter.cpp
fix some minor issues in the comments
=> chore: fix some minor issues in the comments

src/leveldb/README.md
fix comment for src/leveldb/README.md
=> chore: fix comment for src/leveldb/README.md
